http_client:
  max_retries: 3

telegram:
  urls:
    base: https://api.telegram.org
  token: !ENV ${TELEGRAM_BOT_TOKEN}
  channel: !ENV ${TELEGRAM_CHANNEL}

TMdB:
  urls:
    base:  https://api.themoviedb.org
    images: https://image.tmdb.org/
  api_key: !ENV ${TMDB_API_KEY}
  region: FR
  language: fr-FR
  preferences:
    minimal_note: 7
    premium_note: 8
    genres:
      - Thriller
      - Science-Fiction
      - Drame
      - Crime
      - Aventure
      - Fantastique
    excluded_genres:
      - Documentaire
      - Animation