http_client:
  max_retries: 3

telegram:
  base_url: https://api.telegram.org
  token: !ENV ${TELEGRAM_BOT_TOKEN}
  channel: !ENV ${TELEGRAM_CHANNEL}

TMdB:
  base_url: https://api.themoviedb.org
  api_key: !ENV ${TMDB_API_KEY}
  region: FR
  language: fr-FR
  preferences:
    minimal_note: 7
    premium_note: 8
    genres:
      - Thriller
      - Science-Fiction
      - Drame
      - Crime
      - Aventure
      - Fantastique